// <auto-generated />
using System;
using FileShare.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FileShare.Lib.Data.Migrations;

[DbContext(typeof(FileShareContext))]
[Migration("20260822000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("FileShare.Lib.Data.FileEntity", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("AddedDate").HasColumnType("TEXT");
            b.Property<bool>("Completed").HasColumnType("INTEGER");
            b.Property<int>("CompletedBlocks").HasColumnType("INTEGER");
            b.Property<string>("FileName").IsRequired().HasColumnType("TEXT");
            b.Property<long>("FileSize").HasColumnType("INTEGER");
            b.Property<string>("Identifier").IsRequired().HasColumnType("TEXT");
            b.Property<string>("TargetPath").IsRequired().HasColumnType("TEXT");
            b.Property<int>("TotalBlocks").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("Files");
        });

        modelBuilder.Entity("FileShare.Lib.Data.PeerEntity", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<bool>("Connected").HasColumnType("INTEGER");
            b.Property<string>("IPAddress").IsRequired().HasColumnType("TEXT");
            b.Property<DateTime>("LastSeen").HasColumnType("TEXT");
            b.Property<string>("Nickname").IsRequired().HasColumnType("TEXT");
            b.Property<int>("Port").HasColumnType("INTEGER");
            b.Property<string>("RuntimeId").IsRequired().HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("Peers");
        });
#pragma warning restore 612, 618
    }
}
